![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [20]:
my_array= np.array(range(0,10))

my_array[9:0:-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [22]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [24]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [45]:
my_matrix = np.arange(1,21)
my_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
my_matrix = my_matrix.reshape((4,5))
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [60]:
my_matrix[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [62]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [61]:
my_matrix[0:2,0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [63]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
my_matrix[0:3:2,0:6:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [87]:
my_array_inv = my_matrix[::-1,::-1]

my_array_inv

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [92]:
my_array_inv[:3,::-1]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [94]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x

array(['Loro', 'Perro', 'Gato', 'Loro', 'Perro'], dtype='<U5')

In [98]:
mask = (x == "Loro")
x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [106]:
np.where(x=="Loro", "Loro"," ")

array(['Loro', ' ', ' ', 'Loro', ' '], dtype='<U4')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [111]:
secuencia = np.arange(1,21)
secuencia

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [112]:
secuencia.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [114]:
matrix_10 = np.arange(1,21)
matrix_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [116]:
matrix_10 = matrix_10.reshape(4,5)
matrix_10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [117]:
matrix_10[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [185]:
y = np.zeros(10)
y

print(y.itemsize)
print(y.nbytes)

y[3]= 1
y

8
80


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [178]:
x=np.array([1,2,0,0,4,0])
y= np.nonzero(x)
y

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [218]:
z= np.random.randint(101,size=(10,10)) #no olvidar las parentesis en el size
z

array([[ 3, 42, 28,  7, 38,  1, 47, 71, 39, 36],
       [57, 93, 10, 90, 14, 56, 81, 27, 72, 41],
       [43, 17, 88, 41, 36, 86, 37, 63, 26, 99],
       [98, 16,  7, 55,  5, 93, 91, 20, 89, 14],
       [ 9, 85, 57, 78, 79, 99, 22, 78, 23, 66],
       [79,  0,  7, 50, 87,  6, 60, 95, 90, 78],
       [32, 93, 40, 37, 68, 98, 55, 57, 48,  0],
       [96, 32, 55, 88, 13, 69, 18, 19, 83, 69],
       [38, 37, 35,  6, 13, 37, 54, 30, 21, 72],
       [97, 86, 35, 66, 74, 81, 21,  1,  8, 88]])

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [174]:
shape = (30)
vector_al = np.random.randint(1,30, shape)

print(vector_al)
vector_al.mean()

[24 29 16  9  5  7 14 11 12 10  2 26 19 25 22 16 15 10 24 28 11 10  1 13
 23 16 24 11  9  2]


14.8

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [221]:
#intento
cambio = np.full((8,8), 0)
cambio[0] = 1
cambio[-1] = 1
cambio[0,1]

1

In [184]:
reloco = np.ones((8,8))
reloco[1:-1, 1:-1] = 0
reloco

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [227]:
e_17 = np.ones((8,8))
e_17[::,::2] = 1
e_17[::2,::] = 0
e_17

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [205]:
e_17 = np.zeros((8,8))
e_17[::2,::2] = 1
e_17

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [235]:
e_17 = np.ones((8,8))
e_17[::2,1:2:] = 0
e_17[1:2:,::2] = 0
e_17

array([[1., 0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [352]:
e_17 = np.zeros((8,8))
e_17[1::2,0::2] = 1
e_17[::2,1::2] = 1
e_17

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [355]:
np.tile(e_17,1)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [250]:
#intento
matr_al = np.random.rand(5,5)
print(matr_al)

media = matr_al.mean()

for elemento in matr_al:
    resultado = elemento - media
    print(resultado)


[[0.6421016  0.92680247 0.60815862 0.8796382  0.40060742]
 [0.38206039 0.1849519  0.80722265 0.11903854 0.10988452]
 [0.93071826 0.83807862 0.65243106 0.69171024 0.10909041]
 [0.75025803 0.23914757 0.37855101 0.9106043  0.47107451]
 [0.20912652 0.91305002 0.75160121 0.73542862 0.36992682]]
[ 0.08165106  0.36635193  0.04770808  0.31918766 -0.15984312]
[-0.17839015 -0.37549864  0.24677211 -0.441412   -0.45056602]
[ 0.37026772  0.27762808  0.09198052  0.1312597  -0.45136013]
[ 0.18980749 -0.32130297 -0.18189953  0.35015376 -0.08937603]
[-0.35132402  0.35259948  0.19115067  0.17497808 -0.19052372]


In [348]:
matr_al = np.random.rand(5,5)
print(matr_al)

[[0.26228294 0.23587978 0.77577915 0.50831028 0.73677157]
 [0.69067288 0.54240185 0.06701569 0.36352955 0.02498682]
 [0.30694889 0.59413837 0.25804466 0.99949113 0.91567545]
 [0.80079291 0.79088007 0.76520819 0.57757839 0.04275499]
 [0.00264893 0.05158001 0.80196158 0.84050522 0.62703108]]


In [349]:
cosas = matr_al[:] - np.mean(matr_al)
print(cosas)

[[-0.24103187 -0.26743503  0.27246434  0.00499546  0.23345676]
 [ 0.18735806  0.03908703 -0.43629913 -0.13978527 -0.478328  ]
 [-0.19636593  0.09082355 -0.24527015  0.49617631  0.41236064]
 [ 0.29747809  0.28756526  0.26189338  0.07426357 -0.46055982]
 [-0.50066588 -0.4517348   0.29864677  0.33719041  0.12371626]]


In [351]:
cosetes = matr_al[:] - np.mean(matr_al) / np.mean(matr_al)
print(cosetes)

[[-7.37717059e-01 -7.64120218e-01 -2.24220846e-01 -4.91689724e-01
  -2.63228428e-01]
 [-3.09327123e-01 -4.57598154e-01 -9.32984314e-01 -6.36470450e-01
  -9.75013181e-01]
 [-6.93051110e-01 -4.05861634e-01 -7.41955340e-01 -5.08870276e-04
  -8.43245486e-02]
 [-1.99207094e-01 -2.09119930e-01 -2.34791810e-01 -4.22421611e-01
  -9.57245005e-01]
 [-9.97351068e-01 -9.48419988e-01 -1.98038420e-01 -1.59494776e-01
  -3.72968924e-01]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [364]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [365]:
b = a.copy()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [367]:
b[(b >3 ) & (b < 8)] = -1
b

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [ ]:
#esto lo empiezo manana!