![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [64]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
print(my_array.shape)
my_array

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [14]:
pepe = np.array([["True","True","True"],
                ["True","True","True"],
                ["True","True","True"]])
pepe.shape
pepe

array([['True', 'True', 'True'],
       ['True', 'True', 'True'],
       ['True', 'True', 'True']], dtype='<U4')

In [55]:
pepon = np.full((3,3),"True")
pepon

array([['True', 'True', 'True'],
       ['True', 'True', 'True'],
       ['True', 'True', 'True']], dtype='<U4')

## Ejercicio 4
Extrae todos los impares de `my_array`

In [17]:
for numero in my_array:
    if numero %2 != 0:
        print(numero)

1
3
5
7
9


In [81]:
my_array[my_array%2!=0]

array([1, 3, 5, 7, 9])

In [83]:
np.where(my_array%2!=0)

(array([1, 3, 5, 7, 9], dtype=int64),)

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [90]:
np.where(my_array%2!=0,-1,my_array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [48]:
array_5 = my_array.copy()

array_5[array_5 %2 != 0] = -1

array_5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
#las mejores dos formas son la de arriba y la de where

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [91]:
np.where(my_array%2!=0,-1,my_array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [93]:
array2= my_array.reshape((2,5)) #2 dimensiones de 5 columnas
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [102]:
a= np.arange(10).reshape(2,-1)
b= np.repeat(1, 10).reshape(2,-1)
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [98]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.concatenate([a,b], axis =0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#axis0 = filas, hacia abajo
#axis1 = columnas, hacia la derecha

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [109]:
a = np.arange(10).reshape(2,-1) #el -1 te hace el calculo numpy
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b], axis =1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [111]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b, assume_unique=False, return_indices=False)
np.intersect1d([])


array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [112]:
np.concatenate??

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [145]:
my_array= np.array(range(0,10))
print(my_array)

nuevo_array = my_array[my_array]*10
print(nuevo_array)

print(nuevo_array[0])

print(nuevo_array[-1])

print(nuevo_array[1:8])

#for numero in nuevo_array:
    #if numero >= 1 and numero <= 7:
        #print(numero)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
90
[10 20 30 40 50 60 70]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [144]:
my_matrix = np.full((3,3), 1)
my_matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [3]:
secuencia = np.arange(1,50,3)
print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [4]:
secuencia = np.arange(4,1,-0.25)
print(secuencia)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [7]:
import matplotlib.pyplot as plt

imagen = plt.imread("./img/numpy.png")
imagen
imagen.shape

(306, 765, 4)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [150]:
new_array = np.full(4,1)
new_array.reshape((2,2))
#new_array.reshape((2,-1))

array([[1, 1],
       [1, 1]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [155]:
np.array([np.random.rand(5,3), #pensar en voz alta e ir despacito, 4 matrices de 5x3
         np.random.rand(5,3),
         np.random.rand(5,3),
         np.random.rand(5,3)])

np.random.rand(4,5,3)

array([[[0.32399591, 0.73857926, 0.0869225 ],
        [0.14132292, 0.82864311, 0.79725381],
        [0.79786742, 0.88510426, 0.36394994],
        [0.01909771, 0.37390635, 0.40778142],
        [0.82286435, 0.46508343, 0.72015437]],

       [[0.40393176, 0.73157109, 0.90331912],
        [0.26280838, 0.33892299, 0.72478335],
        [0.90352309, 0.76733138, 0.69634757],
        [0.07032856, 0.34297814, 0.40369578],
        [0.64914406, 0.91318968, 0.68152908]],

       [[0.06820052, 0.87364307, 0.69138084],
        [0.00435068, 0.85216482, 0.04719836],
        [0.29297367, 0.01187571, 0.89033495],
        [0.19194273, 0.24708832, 0.81766485],
        [0.08207074, 0.5469734 , 0.8063962 ]],

       [[0.27109753, 0.4662631 , 0.25426991],
        [0.02466784, 0.61636452, 0.61288329],
        [0.29772396, 0.92059294, 0.71484999],
        [0.05383342, 0.24921389, 0.9184274 ],
        [0.52222326, 0.50725214, 0.69650145]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [158]:
pepet = np.full((10,1),"False")
pepet.reshape(2,-1)

array([['False', 'False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False', 'False']], dtype='<U5')

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [160]:
x= np.random.randint(10,20, size = (5,2,6))

x.size

60
3


In [ ]:
x.ndim

In [161]:
for numero in range(x.ndim):
    print(f"La dimension {numero} tiene {x.shape[numero]} elementos")

La dimension 0 tiene 5 elementos
La dimension 1 tiene 2 elementos
La dimension 2 tiene 6 elementos
